version: "3"

services:
  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
      - ./compose/prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - "3060:3000"
    restart: always
