apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
        app: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
      - name: gs-credentials
        secret:
          secretName: gs-credentials
      containers:
      - name: api
        image: asia.gcr.io/k8s-demo-342604/maple_server:latest
        imagePullPolicy: Always
        command: ['gunicorn', 'Maple.wsgi:application', '-b', '0.0.0.0:8000']
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - mountPath: /gs
            name: gs-credentials
        env:
        - name: STATIC_URL
          value: https://storage.googleapis.com/maple-bucket/static/
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DATABASE_HOST
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_NAME
          value: maple
        - name: DATABASE_USER
          value: root
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: DATABASE_PASSWORD
        - name: GS_BUCKET_NAME
          value: maple-bucket
        - name: DJANGO_SETTINGS_MODULE
          value: Maple.settings.gcp
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-secret
              key: SECRET_KEY