# Generated by Django 3.2.11 on 2022-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('line', 'Line'), ('other', '其他')], max_length=8, verbose_name='聯絡方式'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='server_name',
            field=models.CharField(choices=[('jenes', 'jenes'), ('scania', 'scania'), ('luna', 'luna'), ('vindia', 'vindia'), ('kainey', 'kainey')], max_length=8, verbose_name='伺服器'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='total',
            field=models.IntegerField(verbose_name='總額(楓幣)'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='value',
            field=models.IntegerField(verbose_name='幣值(1億楓幣:多少台幣)'),
        ),
    ]
