# Generated by Django 3.2.11 on 2022-07-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_auto_20220626_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='contact_explanation',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='contact_method',
        ),
        migrations.AddField(
            model_name='coin',
            name='contact',
            field=models.JSONField(null=True, verbose_name='聯絡方式'),
        ),
    ]
