# Generated by Django 3.2.11 on 2022-10-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_auto_20220705_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='pay_method',
        ),
    ]
