# Generated by Django 3.2.11 on 2022-02-08 14:58

from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('star', models.IntegerField(verbose_name='星力')),
                ('level', models.IntegerField(verbose_name='裝備等級')),
                ('total_level', models.IntegerField(verbose_name='裝備總等級')),
                ('cut_num', models.IntegerField(blank=True, default=0, verbose_name='剩餘剪刀數')),
                ('attack', models.IntegerField(blank=True, default=0, verbose_name='攻擊力')),
                ('main_attribute', models.CharField(blank=True, max_length=16, verbose_name='主屬性')),
                ('potential_level', models.CharField(choices=[('無', '無'), ('稀有', '稀有'), ('史詩', '史詩'), ('罕見', '罕見'), ('傳說', '傳說')], default='無', max_length=8, verbose_name='淺力等級')),
                ('potential_capability', models.CharField(blank=True, max_length=64, verbose_name='淺力能力')),
                ('spark_level', models.CharField(blank=True, choices=[('罕見', '罕見'), ('傳說', '傳說'), ('神話', '神話')], max_length=8, verbose_name='星火等級')),
                ('spark_capability', models.CharField(blank=True, max_length=64, verbose_name='星火能力')),
                ('is_equippable_soul', models.BooleanField(default=False, verbose_name='可裝備靈魂')),
                ('soul_capability', models.CharField(blank=True, max_length=64, verbose_name='靈魂能力')),
                ('is_maple', models.BooleanField(verbose_name='是否楓葉底')),
                ('maple_capability', models.CharField(choices=[('無', '無'), ('致命傷害', '致命傷害'), ('Boss傷害', 'Boss傷害'), ('Boss防禦', 'Boss防禦'), ('物攻', '物攻'), ('魔攻', '魔攻')], max_length=16, verbose_name='楓底能力')),
                ('maple_level', models.IntegerField(verbose_name='楓底等級')),
                ('price', models.BigIntegerField(verbose_name='價錢')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='說明')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='上架日期')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('product_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('武器', '武器'), ('防具', '防具'), ('造型', '造型'), ('消耗品', '消耗品')], default='武器', max_length=16, verbose_name='類別')),
                ('type', models.CharField(max_length=16, verbose_name='種類')),
                ('name', models.CharField(max_length=16, verbose_name='裝備名稱')),
                ('stage_level', models.CharField(blank=True, choices=[('普通', '普通'), ('稀有', '稀有'), ('史詩', '史詩'), ('罕見', '罕見'), ('傳說', '傳說'), ('神話', '神話'), ('古代', '古代'), ('死靈', '死靈')], default='', max_length=16, verbose_name='階段等級')),
                ('image', models.ImageField(blank=True, upload_to=exchange.models.PathAndRename('product_list_image'), verbose_name='商品列圖片')),
            ],
            options={
                'verbose_name': '商品列',
                'verbose_name_plural': '商品列',
                'ordering': ['pk'],
                'unique_together': {('category', 'type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('product_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=exchange.models.PathAndRename('product_image'), verbose_name='商品圖片')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='exchange.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '裝備圖庫',
                'verbose_name_plural': '裝備圖庫',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.productlist', verbose_name='裝備庫'),
        ),
    ]
