# Generated by Django 3.2.11 on 2022-01-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('weapon', '武器'), ('armor', '防具'), ('skins', '造型'), ('consumables', '消耗品'), ('cooperate', '合作')], default='weapon', max_length=16, verbose_name='類別')),
                ('type', models.CharField(max_length=16, verbose_name='種類')),
                ('name', models.CharField(max_length=16, verbose_name='裝備名稱')),
            ],
            options={
                'verbose_name': '裝備庫',
                'verbose_name_plural': '裝備庫',
            },
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='HistoricalCategory',
        ),
    ]
