# Generated by Django 3.2.11 on 2022-02-09 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='exchange.productlist', verbose_name='裝備庫'),
        ),
    ]
