# Generated by Django 3.2.11 on 2022-04-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maple_capability',
            field=models.CharField(choices=[('無', '無'), ('殘忍的紋章', '殘忍的紋章'), ('征服紋章', '征服紋章'), ('機靈紋章', '機靈紋章'), ('強力紋章', '強力紋章'), ('神聖紋章', '神聖紋章')], default='無', max_length=16, verbose_name='楓底能力'),
        ),
    ]
