# Generated by Django 3.2.11 on 2022-02-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_product_product_list'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productlist',
            unique_together={('category', 'type', 'stage_level', 'name')},
        ),
    ]
