# Generated by Django 3.2.11 on 2022-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_product_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='server_name',
            field=models.CharField(choices=[('jenes', 'jenes'), ('scania', 'scania'), ('luna', 'luna'), ('vindia', 'vindia'), ('kainey', 'kainey')], max_length=8, verbose_name='伺服器'),
        ),
    ]
