# Generated by Django 3.2.11 on 2022-01-29 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_auto_20220129_1026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equiplibrary',
            unique_together={('category', 'type', 'name')},
        ),
    ]
