# Generated by Django 3.2.11 on 2022-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_product_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='maple_capability',
            field=models.CharField(choices=[('null', '無'), ('cruel', '殘忍的紋章'), ('conquer', '征服紋章'), ('clever', '機靈紋章'), ('strong', '強力紋章'), ('sacred', '神聖紋章')], default='null', max_length=16, verbose_name='楓底能力'),
        ),
        migrations.AlterField(
            model_name='product',
            name='potential_level',
            field=models.CharField(choices=[('null', '無'), ('blue', '稀有'), ('purple', '史詩'), ('gold', '罕見'), ('green', '傳說')], default='null', max_length=8, verbose_name='淺力等級'),
        ),
        migrations.AlterField(
            model_name='product',
            name='server_name',
            field=models.CharField(choices=[('jenes', '傑尼斯'), ('scania', '斯卡尼亞'), ('luna', '露娜'), ('vindia', '溫迪亞'), ('kainey', '凱伊尼')], max_length=8, verbose_name='伺服器'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spark_level',
            field=models.CharField(choices=[('null', '無'), ('gold', '罕見'), ('green', '傳說'), ('red', '神話')], default='null', max_length=8, verbose_name='星火等級'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='category',
            field=models.CharField(choices=[('weapon', '武器'), ('armor', '防具'), ('skin', '造型'), ('consume', '消耗品')], default='weapon', max_length=16, verbose_name='類別'),
        ),
    ]
