# Generated by Django 3.2.11 on 2022-01-29 03:21

from django.db import migrations, models
import django.db.models.deletion
import exchange.models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_equiplibrary_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=exchange.models.PathAndRename('equip'), verbose_name='裝備圖片')),
                ('stage_level', models.CharField(blank=True, choices=[('white', '普通'), ('blue', '稀有'), ('purple', '史詩'), ('gold', '罕見'), ('green', '傳說'), ('red', '神話'), ('darkBlue', '古代'), ('deadBlue', '死靈')], default='white', max_length=16, verbose_name='階段等級')),
                ('price', models.BigIntegerField(verbose_name='價錢')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='說明')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='上架日期')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equip', to='exchange.equiplibrary', verbose_name='裝備名稱')),
            ],
            options={
                'verbose_name': '裝備',
                'verbose_name_plural': '裝備',
            },
        ),
    ]
