# Generated by Django 3.2.11 on 2022-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_alter_equip_equip_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiplibrary',
            name='category',
            field=models.CharField(choices=[('武器', 'Weapon'), ('防具', 'Armor'), ('造型', 'Skins'), ('消耗品', 'Consumables'), ('合作', 'Cooperate')], default='武器', max_length=16, verbose_name='類別'),
        ),
    ]
