# Generated by Django 3.2.11 on 2022-01-30 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_equip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equip',
            old_name='picture',
            new_name='images',
        ),
    ]
