# Generated by Django 3.2.11 on 2022-08-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_auto_20220626_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='career',
            field=models.CharField(choices=[('null', '無'), ('archer', '弓箭手'), ('warrior', '戰士'), ('mage', '法師'), ('pirate', '海盜'), ('thieves', '盜賊')], default='null', max_length=8, verbose_name='職業'),
        ),
        migrations.AlterUniqueTogether(
            name='productlist',
            unique_together={('category', 'type', 'stage_level', 'name', 'career')},
        ),
    ]
