# Generated by Django 3.2.11 on 2022-02-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_alter_productlist_product_list_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.BigIntegerField(db_index=True, verbose_name='價錢'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='product_list_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
