# Generated by Django 3.2.11 on 2022-08-23 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20220823_1051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productlist',
            unique_together=set(),
        ),
    ]
