# Generated by Django 3.2.11 on 2022-02-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20220212_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='productlist',
            options={'verbose_name': '商品列', 'verbose_name_plural': '商品列'},
        ),
        migrations.AlterField(
            model_name='productlist',
            name='stage_level',
            field=models.IntegerField(choices=[(0, '無'), (1, '普通'), (2, '稀有'), (3, '史詩'), (4, '罕見'), (5, '傳說'), (6, '神話'), (7, '古代'), (8, '死靈')], default=0, verbose_name='階段等級'),
        ),
    ]
