# Generated by Django 3.2.11 on 2022-02-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20220206_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiplibrary',
            name='max_price',
        ),
        migrations.RemoveField(
            model_name='equiplibrary',
            name='min_price',
        ),
    ]
