# Generated by Django 3.2.11 on 2022-02-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20220214_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='stage_level',
            field=models.CharField(blank=True, choices=[(0, '無'), (1, '普通'), (2, '稀有'), (3, '史詩'), (4, '罕見'), (5, '傳說'), (6, '神話'), (7, '古代'), (8, '死靈')], default='', max_length=16, verbose_name='階段等級'),
        ),
    ]
