# Generated by Django 3.2.11 on 2022-09-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_alter_productlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='stage_level',
            field=models.IntegerField(choices=[(0, '共用'), (1, '普通'), (2, '稀有'), (3, '史詩'), (4, '罕見'), (5, '傳說'), (6, '神話'), (7, '古代')], default=0, verbose_name='階段等級'),
        ),
        migrations.AlterUniqueTogether(
            name='productlist',
            unique_together={('category', 'type', 'stage_level', 'name')},
        ),
    ]
