# Generated by Django 3.2.11 on 2022-02-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20220207_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equip',
            options={'ordering': ['price'], 'verbose_name': '裝備', 'verbose_name_plural': '裝備'},
        ),
        migrations.AlterModelOptions(
            name='equiplibrary',
            options={'ordering': ['pk'], 'verbose_name': '裝備庫', 'verbose_name_plural': '裝備庫'},
        ),
        migrations.AddField(
            model_name='equip',
            name='profession',
            field=models.CharField(default='共用', max_length=64, verbose_name='裝備職業'),
        ),
        migrations.AlterField(
            model_name='equip',
            name='stage_level',
            field=models.CharField(blank=True, choices=[('white', '普通'), ('blue', '稀有'), ('purple', '史詩'), ('gold', '罕見'), ('green', '傳說'), ('red', '神話'), ('darkBlue', '古代'), ('deadBlue', '死靈')], default='white', max_length=16, verbose_name='階段等級'),
        ),
        migrations.AlterField(
            model_name='equiplibrary',
            name='category',
            field=models.CharField(choices=[('weapon', '武器'), ('armor', '防具'), ('skins', '造型'), ('consumables', '消耗品'), ('cooperate', '合作')], default='weapon', max_length=16, verbose_name='類別'),
        ),
    ]
