# Generated by Django 3.2.11 on 2022-09-20 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20220918_2022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productlist',
            unique_together=set(),
        ),
    ]
