# Generated by Django 3.2.11 on 2022-09-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_productlist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='career',
            field=models.CharField(choices=[('null', '無'), ('share', '共用'), ('archer', '弓箭手'), ('sword', '劍士'), ('mage', '法師'), ('pirate', '海盜'), ('thieves', '盜賊')], default='null', max_length=8, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='stage_level',
            field=models.IntegerField(choices=[(0, '普通'), (1, '稀有'), (2, '史詩'), (3, '罕見'), (4, '傳說'), (5, '神話'), (6, '古代')], default=0, verbose_name='階段等級'),
        ),
    ]
