# Generated by Django 3.2.11 on 2022-02-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20220207_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equip',
            name='stage_level',
        ),
        migrations.AddField(
            model_name='equiplibrary',
            name='stage_level',
            field=models.CharField(blank=True, choices=[('white', '普通'), ('blue', '稀有'), ('purple', '史詩'), ('gold', '罕見'), ('green', '傳說'), ('red', '神話'), ('darkBlue', '古代'), ('deadBlue', '死靈')], default='white', max_length=16, verbose_name='階段等級'),
        ),
        migrations.AlterField(
            model_name='equiplibrary',
            name='profession',
            field=models.CharField(default='共用', max_length=64, verbose_name='職業'),
        ),
    ]
