# Generated by Django 3.2.11 on 2022-02-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_productlist_stage_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='potential_capability',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='淺力能力'),
        ),
        migrations.AlterField(
            model_name='product',
            name='soul_capability',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='靈魂能力'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spark_capability',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='星火能力'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='name',
            field=models.CharField(db_index=True, max_length=16, verbose_name='裝備名稱'),
        ),
    ]
