# Generated by Django 3.2.11 on 2022-02-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_auto_20220214_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='spark_level',
            field=models.CharField(blank=True, choices=[('罕見', '罕見'), ('傳說', '傳說'), ('神話', '神話')], max_length=8, null=True, verbose_name='星火等級'),
        ),
    ]
