# Generated by Django 3.2.11 on 2022-10-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_auto_20221007_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='career',
            field=models.CharField(choices=[('null', '無'), ('share', '共用'), ('archer', '弓箭手'), ('warrior', '劍士'), ('mage', '法師'), ('pirate', '海盜'), ('thieves', '盜賊')], default='null', max_length=8, verbose_name='職業'),
        ),
    ]
