# Generated by Django 3.2.11 on 2022-10-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_alter_productlist_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='make_fail_num',
            field=models.IntegerField(default=0, verbose_name='製作失敗次數'),
        ),
        migrations.AddField(
            model_name='product',
            name='surpass_fail_num',
            field=models.IntegerField(default=0, verbose_name='超越失敗次數'),
        ),
    ]
