# Generated by Django 3.2.11 on 2022-02-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_alter_product_product_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_attribute',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='主屬性'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spark_level',
            field=models.CharField(choices=[('無', '無'), ('罕見', '罕見'), ('傳說', '傳說'), ('神話', '神話')], default='無', max_length=8, verbose_name='星火等級'),
        ),
    ]
