# Generated by Django 3.2.11 on 2022-02-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_auto_20220217_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='potential_capability',
            field=models.CharField(default='', max_length=64, verbose_name='淺力能力'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spark_capability',
            field=models.CharField(default='', max_length=64, verbose_name='星火能力'),
        ),
    ]
