# Generated by Django 3.2.11 on 2022-02-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0013_auto_20220217_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': '裝備圖庫2', 'verbose_name_plural': '裝備圖庫2'},
        ),
    ]
