# Generated by Django 3.2.11 on 2022-02-22 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_alter_productimage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品2', 'verbose_name_plural': '商品2'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': '裝備圖庫', 'verbose_name_plural': '裝備圖庫'},
        ),
    ]
