# Generated by Django 3.2.11 on 2022-03-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='provider',
            field=models.CharField(choices=[('無', '無'), ('Google', 'Google')], default='無', max_length=16, verbose_name='註冊方式'),
        ),
    ]
