# Generated by Django 3.2.11 on 2022-03-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='unique_id',
            field=models.CharField(max_length=64, null=True, unique=True, verbose_name='第三方辨識碼'),
        ),
    ]
