# Generated by Django 3.2.11 on 2022-06-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='line_id',
            field=models.CharField(max_length=64, null=True, verbose_name='line id'),
        ),
    ]
