# Generated by Django 3.2.11 on 2022-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='line_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='line id'),
        ),
    ]
