# Generated by Django 3.2.11 on 2022-06-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='server_name',
            field=models.CharField(choices=[('null', '無'), ('jenes', '傑尼斯'), ('scania', '斯卡尼亞'), ('luna', '露娜'), ('vindia', '溫迪亞'), ('kainey', '凱伊尼')], default='null', max_length=8, verbose_name='伺服器'),
        ),
    ]
