# Generated by Django 3.2.11 on 2022-06-26 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='provider',
            field=models.CharField(choices=[('null', '無'), ('google', 'google')], default='null', max_length=16, verbose_name='註冊方式'),
        ),
    ]
