# Generated by Django 3.2.11 on 2022-10-08 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='line_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='contact',
            field=models.JSONField(null=True, verbose_name='聯絡方式'),
        ),
    ]
