# Generated by Django 3.2.11 on 2022-10-30 16:24

import django.core.validators
from django.db import migrations, models
import utils.util


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20221008_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='game_image',
            field=models.ImageField(blank=True, upload_to=utils.util.PathAndRename('game_images'), verbose_name='遊戲截圖'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='game_name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='遊戲名稱'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='遊戲截圖是否驗證'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='手機'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_code',
            field=models.IntegerField(default=0, verbose_name='驗證號碼'),
        ),
    ]
