name: Django CICD

on:
  push:
    branches: [ feature.master.test_github_ci ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DEBUG: False
      DB_NAME: maple
      TEST_DB_NAME: test_maple
      DB_USER: dbuser
      DB_PASSWORD: riu405405
      ROOT_PASSWORD: 123456
      PYTHON_VERSION: 3.7
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.DB_NAME }}
          MYSQL_USER: ${{ env.DB_USER }}
          MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: echo "test ci success"
#      - name: Install Dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install -r requirements.txt
#      - name: Add test Database
#        run: |
#          mysql -uroot -h127.0.0.1 -p'${{ env.ROOT_PASSWORD }}' -e "
#          CREATE DATABASE IF NOT EXISTS ${{ env.TEST_DB_NAME }};
#          CREATE USER ${{ env.DB_USER }}@`%` IDENTIFIED BY '${{ env.DB_PASSWORD }}';
#          GRANT ALL PRIVILEGES ON ${{ env.TEST_DB_NAME }}.* TO ${{ env.DB_USER }}@`%`;
#          select host, user from mysql.user;
#          FLUSH PRIVILEGES;
#          "
##          SHOW DATABASES;
##          select host, user from mysql.user;
#      - name: Run migrate
#        run: python manage.py migrate
#        env:
#          DEBUG: ${{ env.DEBUG }}
#      - name: Run Tests
#        run: python manage.py test --noinput
#        env:
#          DEBUG: ${{ env.DEBUG }}

  deploy:
    name: Deploy Django
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
